### ISSUE TITLE
bitbake error

### ISSUE THREAD

**Issue by arikatlar** [siemens/meta-iot2000#80]
ERROR: Traceback (most recent call last):
  File "/export/home/narikatla/NOS/openembedded-core/bitbake/lib/bb/cookerdata.py", line 178, in wrapped
    return func(fn, *args)
  File "/export/home/narikatla/NOS/openembedded-core/bitbake/lib/bb/cookerdata.py", line 200, in parse_config_file
    return bb.parse.handle(fn, data, include)
  File "/export/home/narikatla/NOS/openembedded-core/bitbake/lib/bb/parse/__init__.py", line 113, in handle
    return h['handle'](fn, data, include)
  File "/export/home/narikatla/NOS/openembedded-core/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 124, in handle
    abs_fn = resolve_file(fn, data)
  File "/export/home/narikatla/NOS/openembedded-core/bitbake/lib/bb/parse/__init__.py", line 136, in resolve_file
    raise IOError(errno.ENOENT, "file %s not found" % fn)
IOError: [Errno 2] file /export/home/narikatla/NOS/meta-rdk-video/conf/layer.conf not found

ERROR: Unable to parse /export/home/narikatla/NOS/meta-rdk-video/conf/layer.conf: [Errno 2] file /export/home/narikatla/NOS/meta-rdk-video/conf/layer.conf not found

please giveme any suggestions

**Comment by jan-kiszka** [comment]
Seems like you are trying to configure an iot2000 build with an additional yocto layer (meta-rdk-video), but you made some mistake in that configuration. You will have to tell us more about what you exactly did, or we cannot help you.

**Comment by arikatlar** [comment]
Hi jan-kisza,

It's a configuration issue, i found it.
Thanks for you reply
